Repository kyma-project/kyma-companion, pull requests merged in 2024-09, with the labels that each got.

#140 feat: introduce plan and route with supervisor
  config/config.yml
  poetry.lock
  pyproject.toml
  scripts/python/generate_langgraph_diagram.py
  src/agents/common/__init__.py
  src/agents/common/agent.py
  src/agents/common/constants.py
  src/agents/common/data.py
  src/agents/common/state.py
  src/agents/common/utils.py
  src/agents/graph.py
  src/agents/k8s/agent.py
  src/agents/k8s/prompts.py
  src/agents/kyma/agent.py
  src/agents/kyma/prompts.py
  src/agents/memory/redis_checkpointer.py
  src/agents/prompts.py
  src/agents/supervisor/agent.py
  src/agents/supervisor/prompts.py
  src/main.py
  src/routers/chat.py
  src/routers/conversations.py
  src/services/chat.py
  src/services/conversation.py
  src/utils/agents.py
  src/utils/config.py
  src/utils/langfuse.py
  src/utils/models.py
  tests/agents/common/test_state.py
  tests/agents/common/test_utils.py
  tests/agents/k8s/test_k8s_agent.py
  tests/agents/kyma/test_kyma_agent.py
  tests/agents/memory/test_redis_checkpointer.py
  tests/agents/supervisor/test_supervisor_agent.py
  tests/routers/test_conversations.py
  tests/services/test_chat.py
  tests/services/test_conversation.py
  tests/utils/test_config.py
  tests/utils/test_models.py
Labels: size/XXL, cla: yes, lgtm

#150 chore: fix blackbox deployment manifests
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/scenario.yml
  tests/blackbox/data/validation/kyma_app_apirule_broken.yml
  tests/blackbox/data/validation/kyma_app_serverless_syntax_err.yml
  tests/blackbox/data/validation/nginx_oom.yml
  tests/blackbox/data/validation/nginx_wrong_image.yml
Labels: size/L, cla: yes, lgtm

#151 chore: fix setup-gardener-test-cluster to deploy/cleanup Kyma modules
  .github/workflows/setup-test-cluster.yaml
  scripts/shell/clean_up_cluster.sh
  scripts/shell/deploy_kyma_modules.sh
Labels: size/M, cla: yes, lgtm

#145 feat: implement initial questions
  poetry.lock
  pyproject.toml
  src/agents/initial_questions/__init__.py
  src/agents/initial_questions/inital_questions.py
  src/agents/initial_questions/output_parser.py
  src/agents/initial_questions/prompts.py
  src/agents/memory/conversation_history.py
  src/agents/memory/redis_checkpointer.py
  src/main.py
  src/routers/common.py
  src/routers/conversations.py
  src/services/conversation.py
  src/services/k8s.py
  src/utils/singleton_meta.py
  src/utils/utils.py
  tests/agents/initial_questions/test_initial_questions.py
  tests/agents/initial_questions/test_output_parser.py
  tests/agents/memory/test_redis_checkpointer.py
  tests/blackbox/src/evaluation/companion/companion.py
  tests/routers/test_conversations.py
  tests/services/test_conversation.py
  tests/services/test_k8s.py
  tests/utils/test_src_utils.py
Labels: size/XXL, cla: yes, lgtm

#153 refactor: rename poe target for more consistency
  pyproject.toml
Labels: cla: yes, size/XS, lgtm

#157 fix: convert conversation id to string
  src/agents/graph.py
  src/routers/conversations.py
  src/services/conversation.py
Labels: cla: yes, size/S, lgtm

#155 test: add kyma related test scenarios
  tests/blackbox/data/evaluation/namespace-scoped/kyma_eventing_wrong_event_type/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/kyma_eventing_wrong_event_type/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_eventing_wrong_event_type/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_serverless_function_no_replicas/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/kyma_serverless_function_no_replicas/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_serverless_function_no_replicas/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_subscription_old_event_type/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/kyma_subscription_old_event_type/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_subscription_old_event_type/scenario.yml
  tests/blackbox/data/validation/kyma_eventing_wrong_event_type.yml
  tests/blackbox/data/validation/kyma_serverless_function_no_replicas.yml
  tests/blackbox/data/validation/kyma_subscription_old_event_type.yml
Labels: cla: yes, lgtm, size/XL

#152 test: add scenarios and validation
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_role_missing/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_role_missing/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_role_missing/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_wrong_rbac_permissions/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_wrong_rbac_permissions/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_wrong_rbac_permissions/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/busybox_no_kubectl_binary/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/busybox_no_kubectl_binary/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/busybox_no_kubectl_binary/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/whoami_too_many_replicas/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/whoami_too_many_replicas/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/whoami_too_many_replicas/scenario.yml
  tests/blackbox/data/validation/bitnami_role_missing.yml
  tests/blackbox/data/validation/bitnami_wrong_rbac_permissions.yml
  tests/blackbox/data/validation/busybox_no_kubectl_binary.yml
  tests/blackbox/data/validation/whoami_too_many_replicas.yml
Labels: cla: yes, lgtm, size/XL

#162 fix: fix file ending
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_role_missing/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_wrong_rbac_permissions/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/busybox_no_kubectl_binary/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/whoami_too_many_replicas/deploy.sh
Labels: cla: yes, size/XS, lgtm

#164 fix: store context instead of initial questions
  poetry.lock
  pyproject.toml
  src/initial_questions/__init__.py
  src/initial_questions/inital_questions.py
  src/initial_questions/output_parser.py
  src/initial_questions/prompts.py
  src/routers/conversations.py
  src/services/conversation.py
  tests/initial_questions/test_initial_questions.py
  tests/initial_questions/test_output_parser.py
  tests/routers/test_conversations.py
  tests/services/test_conversation.py
Labels: size/L, cla: yes, lgtm

#158 chore: update Testing Framework to Replace Mock Responses with Real API Calls
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_role_missing/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/bitnami_wrong_rbac_permissions/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/busybox_no_kubectl_binary/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_eventing_wrong_event_type/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_serverless_function_no_replicas/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_subscription_old_event_type/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/whoami_too_many_replicas/scenario.yml
  tests/blackbox/src/common/config.py
  tests/blackbox/src/common/logger.py
  tests/blackbox/src/common/output.py
  tests/blackbox/src/evaluation/companion/companion.py
  tests/blackbox/src/evaluation/process_scenario.py
  tests/blackbox/src/evaluation/scenario/enums.py
  tests/blackbox/src/evaluation/scenario/scenario.py
  tests/blackbox/src/run_evaluation.py
Labels: size/L, cla: yes, lgtm

#165 chore: improve finalizer prompt
  src/agents/graph.py
  src/agents/prompts.py
Labels: enhancement, size/M, cla: yes, lgtm

#154 feat: improve planner and router
  .gitignore
  poetry.lock
  pyproject.toml
  ruff.toml
  src/agents/common/constants.py
  src/agents/common/state.py
  src/agents/common/utils.py
  src/agents/graph.py
  src/agents/prompts.py
  src/agents/supervisor/agent.py
  src/agents/supervisor/prompts.py
  src/utils/models.py
  tests/agents/common/test_utils.py
  tests/agents/supervisor/test_supervisor_agent.py
Labels: size/XXL, cla: yes, lgtm

#171 refactor: conversation service constructor
  src/services/conversation.py
Labels: cla: yes, size/XS, lgtm

#172 fix: converting k8s context to string
  src/initial_questions/inital_questions.py
  src/services/k8s.py
  tests/initial_questions/test_initial_questions.py
Labels: size/L, cla: yes, lgtm

#163 feat: improve the code and chunk response
  poetry.lock
  pyproject.toml
  scripts/python/generate_langgraph_diagram.py
  src/agents/graph.py
  src/agents/supervisor/agent.py
  src/agents/supervisor/prompts.py
  src/main.py
  src/routers/conversations.py
  src/services/conversation.py
  src/utils/langfuse.py
  src/utils/logging.py
  src/utils/response.py
  src/utils/settings.py
  tests/agents/test_graph.py
  tests/blackbox/src/evaluation/companion/companion.py
  tests/conftest.py
  tests/routers/test_conversations.py
  tests/utils/test_response.py
Labels: size/XXL, cla: yes, lgtm

#175 chore: use gpt-4o-mini
  scripts/python/generate_langgraph_diagram.py
  src/services/conversation.py
  src/utils/models.py
  tests/utils/test_models.py
Labels: cla: yes, size/S, lgtm

#174 feat: apply token limit to initial question generation
  poetry.lock
  pyproject.toml
  src/initial_questions/inital_questions.py
  src/services/conversation.py
  tests/initial_questions/test_initial_questions.py
  tests/services/test_conversation.py
Labels: cla: yes, lgtm, size/XL

#179 fix: use gpt-4o model for planner
  poetry.lock
  src/agents/memory/redis_checkpointer.py
  src/services/conversation.py
  tests/services/test_conversation.py
Labels: size/L, cla: yes, lgtm

#181 chore: create concise plan without extra steps
  src/agents/prompts.py
  src/agents/supervisor/prompts.py
Labels: size/M, cla: yes, lgtm

#180 chore: evaluation test only runs if 'evaluation requested' label is present
  .github/workflows/pull-evaluation-tests.yaml
Labels: cla: yes, size/XS, lgtm, evaluation requested

#185 feat: add comment on gh pr if evaluation was skipped
  .github/workflows/pull-evaluation-tests.yaml
Labels: cla: yes, size/S, lgtm

#189 fix: body of comment
  .github/workflows/pull-evaluation-tests.yaml
Labels: cla: yes, size/XS, lgtm

#192 fix: escape json symbols
  .github/workflows/pull-evaluation-tests.yaml
Labels: cla: yes, size/XS, lgtm

#183 test: install redis-stack
  .github/workflows/pull-evaluation-tests.yaml
  scripts/k8s/companion-deployment.yaml
  tests/blackbox/src/evaluation/scenario/scenario.py
  tests/blackbox/src/run_evaluation.py
Labels: size/M, cla: yes, lgtm
