Repository kyma-project/kyma-companion, pull requests merged in 2024-10, with the labels that each got.

#194 chore: initial version of k8s agent
  .gitignore
  scripts/python/generate_langgraph_diagram.py
  src/agents/common/state.py
  src/agents/common/utils.py
  src/agents/graph.py
  src/agents/k8s/agent.py
  src/agents/k8s/constants.py
  src/agents/k8s/prompts.py
  src/agents/k8s/state.py
  src/agents/k8s/tools/logs.py
  src/agents/k8s/tools/query.py
  src/agents/k8s/utils.py
  src/agents/prompts.py
  src/routers/conversations.py
  src/services/conversation.py
  src/services/k8s.py
  tests/agents/common/test_state.py
  tests/agents/common/test_utils.py
  tests/agents/k8s/test_agent_k8s.py
  tests/agents/k8s/test_agents_k8s_utils.py
  tests/agents/k8s/test_k8s_agent.py
  tests/agents/k8s/tools/test_logs.py
  tests/agents/k8s/tools/test_query.py
  tests/agents/supervisor/test_supervisor_agent.py
  tests/agents/test_graph.py
  tests/routers/test_conversations.py
  tests/services/test_conversation.py
  tests/services/test_k8s.py
Labels: size/XXL, cla: yes, lgtm

#202 fix: change workers to 1
  tests/blackbox/src/common/config.py
Labels: cla: yes, size/XS, lgtm

#205 refactor: blackbox testing
  scripts/shell/deploy_test_scenarios.sh
  tests/blackbox/README.md
  tests/blackbox/data/namespace-scoped/bitnami_role_missing/deploy.sh
  tests/blackbox/data/namespace-scoped/bitnami_role_missing/deployment.yml
  tests/blackbox/data/namespace-scoped/bitnami_role_missing/scenario.yml
  tests/blackbox/data/namespace-scoped/bitnami_role_missing/validation.yml
  tests/blackbox/data/namespace-scoped/bitnami_wrong_rbac_permissions/deploy.sh
  tests/blackbox/data/namespace-scoped/bitnami_wrong_rbac_permissions/deployment.yml
  tests/blackbox/data/namespace-scoped/bitnami_wrong_rbac_permissions/scenario.yml
  tests/blackbox/data/namespace-scoped/bitnami_wrong_rbac_permissions/validation.yml
  tests/blackbox/data/namespace-scoped/busybox_no_kubectl_binary/deploy.sh
  tests/blackbox/data/namespace-scoped/busybox_no_kubectl_binary/deployment.yml
  tests/blackbox/data/namespace-scoped/busybox_no_kubectl_binary/scenario.yml
  tests/blackbox/data/namespace-scoped/busybox_no_kubectl_binary/validation.yml
  tests/blackbox/data/namespace-scoped/kyma_app_apirule_broken/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_app_apirule_broken/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_app_apirule_broken/scenario.yml
  tests/blackbox/data/namespace-scoped/kyma_app_apirule_broken/validation.yml
  tests/blackbox/data/namespace-scoped/kyma_app_serverless_syntax_err/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_app_serverless_syntax_err/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_app_serverless_syntax_err/scenario.yml
  tests/blackbox/data/namespace-scoped/kyma_app_serverless_syntax_err/validation.yml
  tests/blackbox/data/namespace-scoped/kyma_eventing_wrong_event_type/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_eventing_wrong_event_type/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_eventing_wrong_event_type/scenario.yml
  tests/blackbox/data/namespace-scoped/kyma_eventing_wrong_event_type/validation.yml
  tests/blackbox/data/namespace-scoped/kyma_serverless_function_no_replicas/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_serverless_function_no_replicas/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_serverless_function_no_replicas/scenario.yml
  tests/blackbox/data/namespace-scoped/kyma_serverless_function_no_replicas/validation.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_old_event_type/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_subscription_old_event_type/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_old_event_type/scenario.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_old_event_type/validation.yml
  tests/blackbox/data/namespace-scoped/nginx_oom/deploy.sh
  tests/blackbox/data/namespace-scoped/nginx_oom/deployment.yml
  tests/blackbox/data/namespace-scoped/nginx_oom/scenario.yml
  tests/blackbox/data/namespace-scoped/nginx_oom/validation.yml
  tests/blackbox/data/namespace-scoped/nginx_wrong_image/deploy.sh
  tests/blackbox/data/namespace-scoped/nginx_wrong_image/deployment.yml
  tests/blackbox/data/namespace-scoped/nginx_wrong_image/scenario.yml
  tests/blackbox/data/namespace-scoped/nginx_wrong_image/validation.yml
  tests/blackbox/data/namespace-scoped/whoami_too_many_replicas/deploy.sh
  tests/blackbox/data/namespace-scoped/whoami_too_many_replicas/deployment.yml
  tests/blackbox/data/namespace-scoped/whoami_too_many_replicas/scenario.yml
  tests/blackbox/data/namespace-scoped/whoami_too_many_replicas/validation.yml
  tests/blackbox/poetry.lock
  tests/blackbox/pyproject.toml
  tests/blackbox/src/common/config.py
  tests/blackbox/src/run_validation.py
  tests/blackbox/src/test_validation_data.py
  tests/blackbox/src/validation/model_validation.py
  tests/blackbox/src/validation/scenario_mock_responses.py
  tests/blackbox/src/validation/utils/data_loader.py
  tests/blackbox/src/validation/utils/models.py
  tests/blackbox/src/validation/utils/utils.py
  tests/blackbox/src/validation/validator.py
  tests/blackbox/validation.md
Labels: size/XXL, cla: yes, lgtm

#209 chore: moved unit tests under subdirectory
  pyproject.toml
  tests/unit/agents/common/test_state.py
  tests/unit/agents/common/test_utils.py
  tests/unit/agents/k8s/test_agent_k8s.py
  tests/unit/agents/k8s/test_agents_k8s_utils.py
  tests/unit/agents/k8s/tools/test_logs.py
  tests/unit/agents/k8s/tools/test_query.py
  tests/unit/agents/kyma/test_kyma_agent.py
  tests/unit/agents/memory/test_redis_checkpointer.py
  tests/unit/agents/supervisor/test_supervisor_agent.py
  tests/unit/agents/test_graph.py
  tests/unit/conftest.py
  tests/unit/initial_questions/test_initial_questions.py
  tests/unit/initial_questions/test_output_parser.py
  tests/unit/routers/test_conversations.py
  tests/unit/services/test_conversation.py
  tests/unit/services/test_k8s.py
  tests/unit/utils/test_config.py
  tests/unit/utils/test_models.py
  tests/unit/utils/test_response.py
  tests/unit/utils/test_src_utils.py
Labels: cla: yes, size/XS, lgtm

#210 fix: update gen-ai-hub
  tests/blackbox/config/validation/models.yml
  tests/blackbox/poetry.lock
  tests/blackbox/pyproject.toml
  tests/blackbox/src/validation/utils/models.py
Labels: size/XXL, cla: yes, lgtm

#207 chore: rework trigger of Pull Build Image GitHub Action
  .github/workflows/pull-build-image.yaml
  .github/workflows/pull-evaluation-tests.yaml
Labels: size/M, cla: yes, lgtm

#213 feat: use gpt-4o mini in eval tests
  .github/workflows/pull-evaluation-tests.yaml
  tests/blackbox/src/common/config.py
  tests/blackbox/src/evaluation/validator/enums.py
  tests/blackbox/src/evaluation/validator/utils.py
  tests/blackbox/src/evaluation/validator/validator.py
Labels: cla: yes, size/S, lgtm

#212 chore: use smaller model for planner
  .github/workflows/integration-test.yaml
  .gitignore
  README.md
  poetry.lock
  pyproject.toml
  scripts/k8s/companion-deployment.yaml
  scripts/python/generate_langgraph_diagram.py
  src/agents/graph.py
  src/agents/prompts.py
  src/agents/supervisor/agent.py
  src/services/conversation.py
  src/utils/config.py
  src/utils/settings.py
  tests/integration/agents/conftest.py
  tests/integration/agents/test_graph.py
  tests/unit/agents/supervisor/test_supervisor_agent.py
  tests/unit/agents/test_graph.py
  tests/unit/conftest.py
  tests/unit/utils/test_config.py
Labels: size/XXL, cla: yes, lgtm

#221 fix: reference to env var
  tests/blackbox/src/common/config.py
Labels: cla: yes, size/XS, lgtm

#222 chore: update the deployment_id of models
  config/config.yml
Labels: cla: yes, size/XS, lgtm

#218 chore: update-eval-docs
  tests/blackbox/evaluation.md
Labels: cla: yes, size/XS, lgtm

#223 fix: broken var reference in eval test
  .github/workflows/pull-evaluation-tests.yaml
Labels: cla: yes, size/XS, lgtm

#217 chore: added integration tests for K8sClient
  .github/workflows/pull-integration-test.yaml
  .gitignore
  src/services/k8s.py
  tests/integration/services/test_k8s.py
Labels: size/L, cla: yes, lgtm

#228 chore: removed extra commenting on PRs
  .github/workflows/pull-evaluation-tests.yaml
  .github/workflows/pull-integration-test.yaml
Labels: cla: yes, size/S, lgtm

#225 fix: finalizer model call
  src/agents/graph.py
  src/utils/settings.py
Labels: cla: yes, size/XS, lgtm, evaluation requested, run-integration-test

#231 feat: add retry to eval tests
  src/main.py
  tests/blackbox/src/common/config.py
  tests/blackbox/src/evaluation/process_scenario.py
Labels: size/L, cla: yes, lgtm, evaluation requested

#224 feat: sort imports
  poetry.lock
  pyproject.toml
  tests/blackbox/poetry.lock
  tests/blackbox/pyproject.toml
Labels: size/XXL, cla: yes, lgtm, evaluation requested, run-integration-test

#237 feat: add poetry sort to the pre-commit-check
  pyproject.toml
Labels: cla: yes, size/XS, lgtm

#236 refactor: change Validator from interface to protocol
  src/utils/logging.py
  tests/blackbox/src/evaluation/process_scenario.py
  tests/blackbox/src/evaluation/validator/utils.py
  tests/blackbox/src/evaluation/validator/validator.py
  tests/blackbox/src/run_evaluation.py
  tests/blackbox/src/test_validation_data.py
  tests/unit/services/test_conversation.py
Labels: size/M, cla: yes, lgtm, evaluation requested, run-integration-test

#238 chore: enable/disable langfuse using config
  src/utils/langfuse.py
  src/utils/settings.py
  src/utils/utils.py
Labels: cla: yes, size/S, lgtm

#239 feat: implement indexing
  doc_indexer/README.md
  doc_indexer/poetry.lock
  doc_indexer/pyproject.toml
  doc_indexer/ruff.toml
  doc_indexer/src/__init__.py
  doc_indexer/src/indexing/__init__.py
  doc_indexer/src/indexing/contants.py
  doc_indexer/src/indexing/indexer.py
  doc_indexer/src/main.py
  doc_indexer/src/utils/__init__.py
  doc_indexer/src/utils/hana.py
  doc_indexer/src/utils/models.py
  doc_indexer/src/utils/settings.py
  doc_indexer/tests/__init__.py
  doc_indexer/tests/conftest.py
  doc_indexer/tests/integration/__init__.py
  doc_indexer/tests/integration/indexing/__init__.py
  doc_indexer/tests/integration/indexing/test_indexer.py
  doc_indexer/tests/unit/__init__.py
  doc_indexer/tests/unit/fixtures/double_nested_dirs/test-folder-1/sample-1.md
  doc_indexer/tests/unit/fixtures/double_nested_dirs/test-folder-1/test-folder-2/sample-1.md
  doc_indexer/tests/unit/fixtures/single_doc/sample-1.md
  doc_indexer/tests/unit/fixtures/test_docs/test-folder-1/sample-1.md
  doc_indexer/tests/unit/fixtures/test_docs/test-folder-2/sample-1.md
  doc_indexer/tests/unit/fixtures/test_docs/test-folder-2/sample-2.md
  doc_indexer/tests/unit/fixtures/test_docs/test-folder-2/sample-3.md
  doc_indexer/tests/unit/indexing/__init__.py
  doc_indexer/tests/unit/indexing/test_indexer.py
  mypy.ini
  pyproject.toml
Labels: size/XXL, cla: yes, lgtm, run-integration-test

#244 chore: updated documentation for doc_indexer
  doc_indexer/README.md
Labels: cla: yes, size/S, lgtm

#245 chore: improve the Indexer
  doc_indexer/src/indexing/indexer.py
  doc_indexer/src/main.py
  doc_indexer/src/utils/hana.py
  doc_indexer/src/utils/logging.py
  doc_indexer/src/utils/models.py
  doc_indexer/src/utils/settings.py
  doc_indexer/tests/integration/indexing/test_indexer.py
  doc_indexer/tests/unit/indexing/test_indexer.py
  doc_indexer/tests/unit/utils/test_models.py
Labels: size/L, cla: yes, lgtm

#241 feat: added script to pull documents for RAG
  .gitignore
  doc_indexer/.gitignore
  doc_indexer/docs_sources.json
  doc_indexer/poetry.lock
  doc_indexer/pyproject.toml
  doc_indexer/src/fetcher/fetcher.py
  doc_indexer/src/fetcher/scroller.py
  doc_indexer/src/fetcher/source.py
  doc_indexer/src/main.py
  doc_indexer/src/utils/logging.py
  doc_indexer/src/utils/settings.py
  doc_indexer/src/utils/utils.py
  doc_indexer/tests/integration/fetcher/test_docs_sources.json
  doc_indexer/tests/integration/fetcher/test_fetcher.py
  doc_indexer/tests/unit/fetcher/sample_os_walk_output.json
  doc_indexer/tests/unit/fetcher/test_fetcher.py
  doc_indexer/tests/unit/fetcher/test_scroller.py
  doc_indexer/tests/unit/fetcher/test_source.py
  doc_indexer/tests/unit/utils/test_utils.py
Labels: size/XXL, cla: yes, lgtm
