Repository kyma-project/kyma-companion, pull requests merged in 2024-07, with the labels that each got.

#52 Disable testing and release
  .github/workflows/backend-e2e-test.yaml
  .github/workflows/backend-relesase.yaml
Labels: cla: yes, size/S, lgtm

#51 Create initial linting, apis, dockerfile, tests
  .dockerignore
  Dockerfile
  README.md
  config/logging.yaml
  config/models.json
  poetry.lock
  pyproject.toml
  ruff.toml
  src/main.py
  src/rag/__init__.py
  src/routes/api.py
  src/services/__init__.py
  src/services/chat.py
  src/utils/logging.py
  src/utils/models.py
  tests/services/test_chat.py
Labels: size/XXL, cla: yes, lgtm

#56 chore: added dummy implementation of http streaming for chat API
  pyproject.toml
  src/routes/api.py
  src/services/chat.py
  src/utils/utils.py
Labels: size/M, cla: yes, lgtm

#57 chore: added PR title lint job
  .github/workflows/lint-pr-title.yml
Labels: size/M, cla: yes, lgtm

#53 refactor: improve using fastapi and fix running the app locally
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
  src/main.py
  src/routers/__init__.py
  src/routers/chat.py
  src/routes/__init__.py
  src/routes/api.py
  src/services/chat.py
  src/utils/utils.py
  tests/services/test_chat.py
Labels: size/L, cla: yes, lgtm

#61 chore: updated code owners for auto-assign of reviewers
  CODEOWNERS
Labels: cla: yes, size/XS, lgtm

#65 chore: added API for health and readiness
  src/main.py
Labels: cla: yes, size/XS, lgtm

#67 test: github action build test
  .github/workflows/build-test.yaml
Labels: cla: yes, size/S, lgtm

#72 test: build job to use PR version
  .github/workflows/build-test.yaml
  Dockerfile
Labels: size/M, cla: yes

#75 test: fix build github action
  .github/workflows/build-test.yaml
Labels: cla: yes, size/XS, lgtm

#78 chore: python image version
  Dockerfile
Labels: cla: yes, size/XS, lgtm

#71 chore: add build action for the companion image
  .github/workflows/build-image-prod.yaml
Labels: size/M, cla: yes, lgtm

#79 chore: update the pull and push job names
  .github/workflows/build-test.yaml
  .github/workflows/pull-build-image.yaml
  .github/workflows/push-build-image.yaml
Labels: size/M, cla: yes, lgtm

#70 chore: added release pipeline
  .github/workflows/create-release.yml
  hack/scripts/await_pr_merge.sh
  hack/scripts/check_publish_release_prerequisites.sh
  hack/scripts/check_release_tag.sh
  hack/scripts/create_draft_release.sh
  hack/scripts/create_scan_config.sh
  hack/scripts/create_sec_scanner_bump_pr.sh
Labels: size/L, cla: yes, lgtm

#82 chore: update regex for git tag in build job
  .github/workflows/push-build-image.yaml
Labels: cla: yes, size/XS, lgtm

#83 chore: update regex for git tag in build job
  .github/workflows/push-build-image.yaml
Labels: cla: yes, size/XS, lgtm

#69 test: add unit test action
  .github/workflows/unit-test.yaml
Labels: size/M, cla: yes, lgtm

#88 chore: integrate build process in release pipeline
  .github/workflows/create-release.yml
  .github/workflows/tag-build-image.yaml
  hack/scripts/create_draft_release.sh
  poetry.lock
  pyproject.toml
  scripts/python/wait-for-commit-check/requirements.txt
  scripts/python/wait-for-commit-check/run.py
  scripts/shell/await_pr_merge.sh
  scripts/shell/check_publish_release_prerequisites.sh
  scripts/shell/check_release_tag.sh
  scripts/shell/create_draft_release.sh
  scripts/shell/create_git_tag.sh
  scripts/shell/create_scan_config.sh
  scripts/shell/create_sec_scanner_bump_pr.sh
Labels: size/L, cla: yes, lgtm

#89 test: validate the basic functionality of image
  .github/scripts/extract-python-version.sh
  .github/scripts/run-and-check-container.sh
  .github/workflows/pull-build-image.yaml
Labels: size/M, cla: yes, lgtm

#96 fix: failing test by adding checkout code step
  .github/workflows/pull-build-image.yaml
Labels: cla: yes, size/XS, lgtm

#98 chore: add unit test step in release pipeline
  .github/workflows/create-release.yml
  .github/workflows/unit-test.yaml
Labels: cla: yes, size/S, lgtm

#99 chore: move shell scripts to common directory
  .github/workflows/create-release.yml
  .github/workflows/lint-code.yml
  .github/workflows/pull-build-image.yaml
  .github/workflows/unit-test.yaml
  scripts/shell/extract-python-version.sh
  scripts/shell/run-and-check-container.sh
Labels: cla: yes, size/XS, lgtm

#97 fix: use `jq` to extract image name
  .github/workflows/pull-build-image.yaml
Labels: cla: yes, size/S, lgtm

#68 feat: create session management
  README.md
  config/config.yml
  config/logging.yml
  config/models.json
  poetry.lock
  pyproject.toml
  src/agents/memory/__init__.py
  src/agents/memory/redis_checkpointer.py
  src/agents/supervisor/__init__.py
  src/agents/supervisor/agent.py
  src/main.py
  src/routers/chat.py
  src/services/chat.py
  src/utils/agents.py
  src/utils/config.py
  src/utils/logging.py
  src/utils/models.py
  tests/agents/memory/test_redis_checkpointer.py
  tests/services/test_chat.py
  tests/utils/test_config.py
  tests/utils/test_models.py
Labels: size/XXL, cla: yes, lgtm

#101 chore: removed sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: cla: yes, size/S, lgtm
