Repository kyma-project/kyma-companion, pull requests merged in 2024-11, with the labels that each got.

#219 refactor: unite supervisor in one subgraph
  scripts/python/generate_langgraph_diagram.py
  src/agents/common/state.py
  src/agents/common/utils.py
  src/agents/graph.py
  src/agents/k8s/agent.py
  src/agents/k8s/state.py
  src/agents/prompts.py
  src/agents/supervisor/agent.py
  src/agents/supervisor/prompts.py
  src/agents/supervisor/state.py
  src/services/conversation.py
  src/utils/response.py
  tests/blackbox/src/evaluation/companion/companion.py
  tests/integration/agents/conftest.py
  tests/integration/agents/test_graph.py
  tests/unit/agents/supervisor/test_supervisor_agent.py
  tests/unit/agents/test_graph.py
  tests/unit/routers/test_conversations.py
  tests/unit/services/test_conversation.py
  tests/unit/utils/test_response.py
Labels: size/XXL, cla: yes, lgtm, evaluation requested, run-integration-test

#248 fix: fix doc_indexer actions
  .github/workflows/pull-lint-doc-indexer.yaml
  .github/workflows/pull-tests-doc-indexer.yaml
Labels: cla: yes, size/XS, lgtm

#249 fix: fix tests github action of doc_indexer
  .github/workflows/pull-lint-doc-indexer.yaml
  .github/workflows/pull-tests-doc-indexer.yaml
Labels: cla: yes, size/XS, lgtm

#260 fix: make temperature for models optional
  src/utils/config.py
Labels: cla: yes, size/XS, lgtm, run-integration-test

#252 feat: implement initial version of follow-up questions endpoint
  .gitignore
  poetry.lock
  pyproject.toml
  src/agents/graph.py
  src/followup_questions/__init__.py
  src/followup_questions/constants.py
  src/followup_questions/followup_questions.py
  src/followup_questions/prompts.py
  src/routers/common.py
  src/routers/conversations.py
  src/services/conversation.py
  tests/integration/agents/test_followup_questions.py
  tests/unit/agents/test_graph.py
  tests/unit/followup_questions/test_followup_questions.py
  tests/unit/routers/test_conversations.py
  tests/unit/services/test_conversation.py
Labels: cla: yes, lgtm, size/XL

#262 fix: add hana db config to companion k8s deployment
  .github/workflows/pull-evaluation-tests.yaml
  scripts/k8s/companion-deployment.yaml
  src/rag/retriever.py
Labels: size/M, cla: yes, lgtm, evaluation requested

#264 chore: remove redis history
  pyproject.toml
  src/routers/conversations.py
  src/services/conversation.py
  tests/unit/routers/test_conversations.py
  tests/unit/services/test_conversation.py
Labels: size/M, cla: yes, lgtm, evaluation requested, run-integration-test

#265 refactor: clean up imports
  src/agents/memory/redis_checkpointer.py
  src/agents/supervisor/agent.py
Labels: cla: yes, size/S, lgtm, evaluation requested, run-integration-test

#267 feat: implement kyma doc rag system
  .github/workflows/pull-integration-test.yaml
  .vscode/settings.json
  doc_indexer/.vscode/launch.json
  poetry.lock
  pyproject.toml
  src/agents/common/agent.py
  src/agents/common/utils.py
  src/agents/kyma/agent.py
  src/agents/kyma/prompts.py
  src/agents/kyma/tools/search.py
  src/agents/supervisor/agent.py
  src/agents/supervisor/prompts.py
  src/rag/generator.py
  src/rag/prompts.py
  src/rag/query_generator.py
  src/rag/retriever.py
  src/rag/system.py
  tests/integration/agents/kyma/test_kyma_agent.py
  tests/integration/agents/test_graph.py
  tests/integration/conftest.py
  tests/integration/rag/fixtures/kyma_docs/eventing-manager/docs/user/troubleshooting/evnt-04-free-jetstream-storage.md
  tests/integration/rag/fixtures/kyma_docs/eventing-manager/docs/user/troubleshooting/evnt-05-fix-pending-messages.md
  tests/integration/rag/fixtures/kyma_docs/istio/docs/user/troubleshooting/03-20-connection-refused.md
  tests/integration/rag/fixtures/kyma_docs/istio/docs/user/troubleshooting/03-30-istio-no-sidecar.md
  tests/integration/rag/fixtures/kyma_docs/istio/docs/user/tutorials/01-40-enable-sidecar-injection.md
  tests/integration/rag/fixtures/kyma_docs/serverless/docs/user/troubleshooting-guides/03-40-function-build-failing-k3d.md
  tests/integration/rag/fixtures/kyma_docs/serverless/docs/user/troubleshooting-guides/03-50-serverless-periodically-restaring.md
  tests/integration/rag/fixtures/kyma_docs/serverless/docs/user/tutorials/01-10-create-inline-function.md
  tests/integration/rag/fixtures/kyma_docs/serverless/docs/user/tutorials/01-100-customize-function-traces.md
  tests/integration/rag/fixtures/kyma_docs/serverless/docs/user/tutorials/01-110-override-runtime-image.md
  tests/integration/rag/fixtures/kyma_docs/serverless/docs/user/tutorials/01-120-inject-envs.md
  tests/integration/rag/fixtures/kyma_docs/serverless/docs/user/tutorials/01-20-expose-function.md
  tests/integration/rag/fixtures/kyma_docs/telemetry-manager/docs/user/02-logs.md
  tests/integration/rag/fixtures/kyma_docs/telemetry-manager/docs/user/resources/04-tracepipeline.md
  tests/integration/rag/test_query_generator.py
  tests/integration/rag/test_rag_system.py
  tests/unit/agents/common/test_utils.py
  tests/unit/agents/kyma/test_kyma_agent.py
  tests/unit/rag/test_generator.py
  tests/unit/rag/test_query_generator.py
  tests/unit/rag/test_retriever.py
Labels: size/XXL, cla: yes, lgtm, evaluation requested

#297 fix: correct hana db var name
  .github/workflows/pull-integration-test.yaml
Labels: cla: yes, size/XS, lgtm

#299 chore: added undeploy script in blackbox test cases
  .github/workflows/setup-test-cluster.yaml
  .gitignore
  scripts/shell/clean_up_cluster.sh
  scripts/shell/deploy_kyma_modules.sh
  scripts/shell/undeploy_test_scenarios.sh
  tests/blackbox/data/namespace-scoped/bitnami_role_missing/undeploy.sh
  tests/blackbox/data/namespace-scoped/bitnami_wrong_rbac_permissions/undeploy.sh
  tests/blackbox/data/namespace-scoped/busybox_no_kubectl_binary/undeploy.sh
  tests/blackbox/data/namespace-scoped/kyma_app_apirule_broken/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_app_apirule_broken/undeploy.sh
  tests/blackbox/data/namespace-scoped/kyma_app_serverless_syntax_err/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_app_serverless_syntax_err/undeploy.sh
  tests/blackbox/data/namespace-scoped/kyma_eventing_wrong_event_type/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_eventing_wrong_event_type/undeploy.sh
  tests/blackbox/data/namespace-scoped/kyma_serverless_function_no_replicas/undeploy.sh
  tests/blackbox/data/namespace-scoped/kyma_subscription_old_event_type/undeploy.sh
  tests/blackbox/data/namespace-scoped/nginx_oom/undeploy.sh
  tests/blackbox/data/namespace-scoped/nginx_wrong_image/undeploy.sh
  tests/blackbox/data/namespace-scoped/whoami_too_many_replicas/deploy.sh
  tests/blackbox/data/namespace-scoped/whoami_too_many_replicas/undeploy.sh
Labels: size/L, cla: yes, lgtm

#298 fix: make finalizer less restrictive
  poetry.lock
  pyproject.toml
  src/agents/supervisor/prompts.py
  tests/integration/agents/kyma/test_kyma_agent.py
  tests/integration/agents/supervisor/test_finalizer.py
  tests/integration/agents/supervisor/test_planner.py
  tests/integration/agents/supervisor/test_router.py
  tests/integration/agents/test_common_node.py
  tests/integration/agents/test_followup_questions.py
  tests/integration/agents/test_graph.py
  tests/integration/conftest.py
  tests/integration/rag/test_query_generator.py
  tests/integration/rag/test_rag_system.py
Labels: size/XXL, cla: yes, lgtm, evaluation requested, run-integration-test
