Repository kyma-project/kyma-companion, pull requests merged in 2024-08, with the labels that each got.

#104 chore: refine version number for image builder
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
Labels: size/L, cla: yes, lgtm

#103 docs: update readme
  README.md
  pyproject.toml
Labels: size/M, cla: yes, lgtm

#105 feat: integrate job to build companion image and provision Kyma cluster
  .github/workflows/test-companion.yaml
  .gitignore
  scripts/k8s/companion-deployment.yaml
  scripts/k8s/companion-namespace.yaml
  scripts/python/wait-for-commit-check/run.py
  scripts/shell/deploy-wait-for-deployment.sh
Labels: size/L, cla: yes, lgtm

#109 chore: remove hdbcli
  poetry.lock
  pyproject.toml
Labels: cla: yes, size/S, lgtm

#106 test: basic action for setup of test cluster
  .github/workflows/setup-test-cluster.yaml
Labels: size/M, cla: yes, lgtm

#116 chore: add tech writers as codeowners
  CODEOWNERS
Labels: cla: yes, size/XS, lgtm

#119 chore: added documentation of Blackbox evaluation tests
  .gitignore
  tests/blackbox/evaluation/README.md
  tests/blackbox/evaluation/src/common/config.py
Labels: size/M, cla: yes, lgtm

#123 fix: fix model name for GPT4o
  scripts/k8s/companion-deployment.yaml
  src/services/chat.py
  src/utils/config.py
  src/utils/models.py
Labels: cla: yes, size/S, lgtm

#118 test: clean up gardener cluster
  .github/workflows/setup-test-cluster.yaml
  scripts/shell/clean_up_cluster.sh
Labels: size/L, cla: yes, lgtm

#124 chore: update deployment file for companion
  .gitignore
  scripts/k8s/.gitignore
  scripts/k8s/companion-deployment.yaml
  src/utils/config.py
Labels: size/M, cla: yes, lgtm

#121 test: add script to deploy test cases
  .github/workflows/setup-test-cluster.yaml
  scripts/shell/deploy_test_scenarios.sh
Labels: size/M, cla: yes, lgtm

#128 chore: adapt secret reading for new ai core secret format
  .github/workflows/validate-models.yml
Labels: cla: yes, size/S, lgtm

#129 fix: correct path in script
  scripts/shell/deploy_test_scenarios.sh
Labels: cla: yes, size/XS, lgtm

#130 chore: fix mispelliung of secret vars
  .github/workflows/validate-models.yml
Labels: cla: yes, size/XS, lgtm

#127 docs: document testing
  tests/blackbox/evaluation.md
Labels: cla: yes, size/XS, lgtm

#131 fix: revert evaluation data
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/deployment.yml
  tests/blackbox/validation.md
Labels: size/M, cla: yes, lgtm

#132 fix: make deploy script executable
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/deploy.sh
Labels: cla: yes, size/XS, lgtm

#125 docs: documentation update
  README.md
  docs/README.md
  docs/contributor/README.md
  docs/contributor/release-process.md
  docs/contributor/release-testing.md
  docs/images/release-process-workflow-steps.png
  docs/images/release-testing-workflow-steps.png
  docs/user/README.md
  docs/user/_sidebar.md
Labels: documentation, cla: yes, lgtm, size/XL

#135 chore: added readiness and liveness probes in deployment
  .gitignore
  scripts/k8s/companion-deployment.yaml
  tests/blackbox/pyproject.toml
  tests/blackbox/src/evaluation/companion/companion.py
Labels: cla: yes, size/S, lgtm

#134 chore: integrate evaluation tests in github action
  .github/workflows/pull-evaluation-tests.yaml
  .github/workflows/test-companion.yaml
Labels: size/L, cla: yes, lgtm

#133 chore: adding testing scenarios
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/deploy.sh
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/deployment.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/scenario.yml
  tests/blackbox/data/validation/kyma_app_apirule_broken.yml
  tests/blackbox/data/validation/kyma_app_serverless_syntax_err.yml
  tests/blackbox/data/validation/nginx_oom.yml
  tests/blackbox/data/validation/nginx_wrong_image.yml
Labels: cla: yes, lgtm, size/XL

#137 feat: load validations as list from file
  tests/blackbox/data/validation/kyma_app_apirule_broken.yml
  tests/blackbox/data/validation/kyma_app_serverless_syntax_err.yml
  tests/blackbox/data/validation/nginx_oom.yml
  tests/blackbox/data/validation/nginx_wrong_image.yml
  tests/blackbox/src/validation/utils/data_loader.py
Labels: size/L, cla: yes, lgtm

#147 chore: measure response times of Companion endpoints in blackbox tests
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_apirule_broken/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/kyma_app_serverless_syntax_err/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_oom/scenario.yml
  tests/blackbox/data/evaluation/namespace-scoped/nginx_wrong_image/scenario.yml
  tests/blackbox/src/common/metrics.py
  tests/blackbox/src/common/output.py
  tests/blackbox/src/evaluation/companion/companion.py
  tests/blackbox/src/evaluation/scenario/scenario.py
  tests/blackbox/src/run_evaluation.py
Labels: size/L, cla: yes, lgtm
