Repository kyma-project/kyma-companion, pull requests merged in 2024-05, with the labels that each got.

#11 Reuse tool
  .reuse/dep5
  README.md
Labels: cla: yes, size/S, lgtm

#14 Test Automation & Release process
  .github/workflows/backend-relesase.yaml
  .github/workflows/pull-gitleaks.yml
  README.md
  assistant/backend/Dockerfile
  docs/contributor/README.md
  docs/contributor/release-testing.md
Labels: enhancement, size/M, cla: yes, lgtm

#15 fix: Use the right variable for IMAGE_REGISTRY
  .github/workflows/backend-relesase.yaml
Labels: cla: yes, size/XS, lgtm
