Repository kyma-project/kyma-companion, pull requests merged in 2025-01, with the labels that each got.

#326 fix: remove `--no-dev` instruction from `poetry install` in dockerfile
  Dockerfile
Labels: cla: yes, size/XS, lgtm

#329 chore: exclude dev and test packages from build
  Dockerfile
  poetry.lock
  pyproject.toml
Labels: size/XXL, cla: yes, lgtm

#332 chore: add security scanners config
  sec-scanners-config.yaml
Labels: cla: yes, size/S, lgtm

#320 chore: added k8s related test cases in blackbox tests
  .gitignore
  tests/blackbox/data/namespace-scoped/k8s_improper_persistent_storage/deploy.sh
  tests/blackbox/data/namespace-scoped/k8s_improper_persistent_storage/deployment.yml
  tests/blackbox/data/namespace-scoped/k8s_improper_persistent_storage/scenario.yml
  tests/blackbox/data/namespace-scoped/k8s_improper_persistent_storage/undeploy.sh
  tests/blackbox/data/namespace-scoped/k8s_improper_persistent_storage/validation.yml
  tests/blackbox/data/namespace-scoped/k8s_incorrect_liveness_probe/deploy.sh
  tests/blackbox/data/namespace-scoped/k8s_incorrect_liveness_probe/deployment.yml
  tests/blackbox/data/namespace-scoped/k8s_incorrect_liveness_probe/scenario.yml
  tests/blackbox/data/namespace-scoped/k8s_incorrect_liveness_probe/undeploy.sh
  tests/blackbox/data/namespace-scoped/k8s_incorrect_liveness_probe/validation.yml
  tests/blackbox/data/namespace-scoped/k8s_wrong_svc_labels/deploy.sh
  tests/blackbox/data/namespace-scoped/k8s_wrong_svc_labels/deployment.yml
  tests/blackbox/data/namespace-scoped/k8s_wrong_svc_labels/scenario.yml
  tests/blackbox/data/namespace-scoped/k8s_wrong_svc_labels/undeploy.sh
  tests/blackbox/data/namespace-scoped/k8s_wrong_svc_labels/validation.yml
Labels: cla: yes, lgtm, size/XL, evaluation requested

#333 chore: remove unused env var for HANA db credentials
  .github/workflows/pull-evaluation-tests.yaml
  src/main.py
Labels: cla: yes, size/XS, lgtm, evaluation requested

#334 chore: pin the version of petry used in the dockerfile
  Dockerfile
Labels: cla: yes, size/XS, lgtm

#309 chore: improve finalizer prompt to include yamls
  src/agents/supervisor/prompts.py
  tests/integration/agents/supervisor/test_finalizer.py
  tests/integration/conftest.py
Labels: cla: yes, size/S, lgtm, evaluation requested, run-integration-test

#328 chore: add blackbox tests for Kyma
  tests/blackbox/data/namespace-scoped/kyma_function_syntax_error/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_function_syntax_error/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_function_syntax_error/scenario.yml
  tests/blackbox/data/namespace-scoped/kyma_function_syntax_error/undeploy.sh
  tests/blackbox/data/namespace-scoped/kyma_function_syntax_error/validation.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_sink/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_sink/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_sink/scenario.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_sink/undeploy.sh
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_sink/validation.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_source/deploy.sh
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_source/deployment.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_source/scenario.yml
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_source/undeploy.sh
  tests/blackbox/data/namespace-scoped/kyma_subscription_invalid_source/validation.yml
  tests/blackbox/src/evaluation/process_scenario.py
Labels: size/L, cla: yes, lgtm, run-integration-test

#338 chore: use separate GHA secret for int tests
  .github/workflows/pull-integration-test.yaml
Labels: cla: yes, size/XS, lgtm

#341 feat: add user, password and database-number as configurables to build redis URL
  src/utils/settings.py
Labels: cla: yes, size/XS, lgtm, evaluation requested, run-integration-test

#322 feat: add summarization node for messages in graph state
  .gitignore
  poetry.lock
  pyproject.toml
  src/agents/common/agent.py
  src/agents/common/constants.py
  src/agents/common/state.py
  src/agents/common/utils.py
  src/agents/graph.py
  src/agents/summarization/__init__.py
  src/agents/summarization/prompts.py
  src/agents/summarization/summarization.py
  src/agents/supervisor/agent.py
  src/utils/filter_messages.py
  src/utils/logging.py
  src/utils/settings.py
  tests/integration/agents/kyma/test_kyma_agent.py
  tests/integration/agents/summarization/fixtures/messages.py
  tests/integration/agents/summarization/test_summarization.py
  tests/unit/agents/common/test_agent.py
  tests/unit/agents/common/test_state.py
  tests/unit/agents/common/test_utils.py
  tests/unit/agents/k8s/test_k8s_agent.py
  tests/unit/agents/kyma/test_kyma_agent.py
  tests/unit/agents/summarization/test_summarization.py
  tests/unit/agents/test_graph.py
  tests/unit/utils/test_filter_messages.py
Labels: size/XXL, cla: yes, lgtm, evaluation requested, run-integration-test

#342 chore: updated release pipeline
  .github/workflows/create-release.yml
  .github/workflows/pull-integration-test.yaml
  scripts/shell/check_publish_release_prerequisites.sh
  scripts/shell/create_scan_config.sh
  scripts/shell/create_sec_scanner_bump_pr.sh
Labels: size/L, cla: yes, lgtm

#330 feat: sanitize sensitive information
  poetry.lock
  pyproject.toml
  src/agents/k8s/tools/query.py
  src/agents/kyma/tools/query.py
  src/agents/memory/async_redis_checkpointer.py
  src/agents/memory/conversation_history.py
  src/agents/memory/redis_checkpointer.py
  src/routers/conversations.py
  src/services/conversation.py
  src/services/data_sanitizer.py
  src/services/k8s.py
  src/utils/config.py
  src/utils/models/factory.py
  tests/integration/conftest.py
  tests/integration/services/test_k8s.py
  tests/unit/agents/k8s/tools/test_query.py
  tests/unit/agents/memory/test_async_redis_checkpointer.py
  tests/unit/agents/memory/test_redis_checkpointer.py
  tests/unit/conftest.py
  tests/unit/routers/test_conversations.py
  tests/unit/services/test_conversation.py
  tests/unit/services/test_data_sanitizer.py
  tests/unit/services/test_k8s.py
  tests/unit/utils/test_config.py
  tests/unit/utils/test_factory.py
Labels: size/XXL, cla: yes, lgtm, evaluation requested, run-integration-test

#344 fix: fix release pipeline
  .github/workflows/create-release.yml
Labels: cla: yes, size/XS, lgtm

#350 fix: update enhance query generation error handling
  poetry.lock
  src/rag/query_generator.py
  tests/unit/rag/test_query_generator.py
Labels: size/L, cla: yes, lgtm, run-integration-test

#331 feat: added rate limiter
  src/agents/common/constants.py
  src/agents/common/utils.py
  src/agents/graph.py
  src/routers/conversations.py
  src/services/conversation.py
  src/services/k8s.py
  src/services/langfuse.py
  src/utils/common.py
  src/utils/langfuse.py
  src/utils/settings.py
  tests/integration/services/__init__.py
  tests/integration/services/test_langfuse.py
  tests/unit/agents/test_graph.py
  tests/unit/services/__init__.py
  tests/unit/services/test_langfuse.py
Labels: cla: yes, lgtm, size/XL, evaluation requested, run-integration-test

#318 feat: added response conversion node
  src/agents/common/constants.py
  src/agents/common/response_converter.py
  src/agents/supervisor/agent.py
  src/agents/supervisor/prompts.py
  tests/unit/agents/common/test_response_converter.py
  tests/unit/agents/test_graph.py
Labels: cla: yes, lgtm, size/XL, evaluation requested, run-integration-test

#357 chore: enhance data sanitizer to remove last-applied-configuration
  src/services/data_sanitizer.py
  tests/unit/services/test_data_sanitizer.py
Labels: size/L, cla: yes, lgtm, evaluation requested, run-integration-test

#348 chore: refactor configs
  .github/workflows/backend-e2e-test.yaml
  .github/workflows/backend-relesase.yaml
  src/utils/settings.py
  tests/blackbox/poetry.lock
  tests/blackbox/pyproject.toml
  tests/blackbox/src/common/config.py
  tests/blackbox/src/common/utils.py
  tests/blackbox/src/evaluation/validator/enums.py
  tests/blackbox/src/evaluation/validator/utils.py
  tests/blackbox/src/evaluation/validator/validator.py
  tests/blackbox/src/run_validation.py
  tests/blackbox/src/validation/utils/models.py
Labels: cla: yes, lgtm, size/XL

#356 chore: update integration and evaluation tests pipelines
  .github/workflows/create-release.yml
  .github/workflows/pull-evaluation-tests.yaml
  .github/workflows/pull-integration-test.yaml
  .github/workflows/validate-models.yml
  scripts/k8s/companion-deployment.yaml
  scripts/k8s/companion-k3d-manifest.yaml
  scripts/k8s/companion-namespace.yaml
  scripts/k8s/create-secret.sh
Labels: size/L, cla: yes, lgtm

#360 chore: updated doc_indexer github action
  .github/workflows/pull-tests-doc-indexer.yaml
Labels: size/M, cla: yes, lgtm

#359 fix: updated doc_indexer to use config file
  doc_indexer/src/main.py
  doc_indexer/src/utils/model_config.py
  doc_indexer/src/utils/settings.py
  doc_indexer/tests/integration/indexing/test_indexer.py
Labels: size/M, cla: yes, lgtm

#362 chore: updated documentation
  README.md
  config/config-example.json
  doc_indexer/README.md
  tests/blackbox/evaluation.md
  tests/blackbox/validation.md
  tests/integration/README.md
Labels: size/L, cla: yes, lgtm
