Repository kyma-project/kyma-companion, pull requests merged in 2025-02, with the labels that each got.

#366 feat: langfuse prod/debug mode
  src/services/langfuse.py
  src/utils/settings.py
Labels: size/M, cla: yes, lgtm, run-integration-test

#367 feat: start options to support debugpy
  src/main.py
Labels: cla: yes, size/XS, lgtm, evaluation requested, run-integration-test

#347 docs: deploy langfuse for development
  docs/langfuse.md
Labels: size/L, cla: yes, lgtm

#358 feat: shorten intermediate outputs of the companion
  src/agents/common/agent.py
  src/agents/common/constants.py
  src/agents/common/state.py
  src/agents/graph.py
  src/agents/supervisor/agent.py
  src/agents/supervisor/prompts.py
  src/routers/conversations.py
  src/utils/response.py
  tests/integration/agents/kyma/test_kyma_agent.py
  tests/integration/agents/supervisor/test_planner.py
  tests/integration/agents/supervisor/test_router.py
  tests/unit/agents/common/test_agent.py
  tests/unit/agents/common/test_state.py
  tests/unit/agents/common/test_utils.py
  tests/unit/agents/supervisor/test_supervisor_agent.py
  tests/unit/agents/test_graph.py
  tests/unit/routers/test_conversations.py
  tests/unit/utils/test_response.py
Labels: cla: yes, lgtm, size/XL, evaluation requested, run-integration-test

#374 docs: add langfuse section in readme
  README.md
  config/config-example.json
  docs/langfuse.md
Labels: size/L, cla: yes, lgtm

#378 chore: remove file logging
  config/logging.yml
Labels: cla: yes, size/XS, lgtm

#382 chore: updated comment for root API
  src/main.py
Labels: cla: yes, size/XS, lgtm

#385 fix: made resource_name as optional parameter for initial questions
  src/routers/common.py
Labels: cla: yes, size/XS, lgtm, evaluation requested, run-integration-test

#387 chore: add langfuse images to sec-scanners-config
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm

#386 chore: build job ignores changes to sec-scanners-config
  .github/workflows/pull-build-image.yaml
Labels: cla: yes, size/XS

#388 chore: enhance kyma, k8s agents and reranker
  src/agents/k8s/prompts.py
  src/agents/kyma/agent.py
  src/agents/kyma/prompts.py
  src/rag/system.py
  tests/integration/rag/test_rag_system.py
Labels: size/M, cla: yes, lgtm, evaluation requested, run-integration-test

#379 chore: enhance error handling for summarization node
  scripts/python/generate_langgraph_diagram.py
  src/agents/common/agent.py
  src/agents/common/state.py
  src/agents/common/utils.py
  src/agents/graph.py
  src/agents/summarization/summarization.py
  src/utils/response.py
  tests/integration/agents/summarization/test_summarization.py
  tests/unit/agents/common/test_agent.py
  tests/unit/agents/summarization/test_summarization.py
Labels: size/L, cla: yes, lgtm, evaluation requested, run-integration-test

#400 fix: fixed default path for project root
  doc_indexer/src/utils/settings.py
Labels: cla: yes, size/XS

#393 chore: error handling finalizer
  src/agents/common/agent.py
  src/agents/common/state.py
  src/agents/supervisor/agent.py
  tests/unit/agents/common/test_agent.py
  tests/unit/agents/supervisor/test_supervisor_agent.py
Labels: size/L, cla: yes, lgtm, evaluation requested, run-integration-test

#405 chore: limit permissions of lint and unit
  .github/workflows/lint-code.yml
  .github/workflows/lint-pr-title.yml
  .github/workflows/unit-test.yaml
Labels: cla: yes, size/S, lgtm

#403 chore: add the zookeeper image to our sec-scanner-config
  .github/workflows/unit-test.yaml
  sec-scanners-config.yaml
Labels: cla: yes, size/XS, lgtm

#402 chore: added authorization for conversation
  poetry.lock
  pyproject.toml
  src/agents/common/state.py
  src/agents/graph.py
  src/routers/conversations.py
  src/services/conversation.py
  src/utils/utils.py
  tests/unit/agents/test_graph.py
  tests/unit/routers/test_conversations.py
  tests/unit/services/test_conversation.py
  tests/unit/utils/test_src_utils.py
Labels: cla: yes, lgtm, size/XL, evaluation requested, run-integration-test

#408 chore: set permissions of integration test workflow
  .github/workflows/pull-integration-test.yaml
Labels: size/XS, run-integration-test

#372 docs: address uvicorn as a start option
  README.md
Labels: cla: yes, size/S, lgtm
