Repository kyma-project/kyma-companion, pull requests merged in 2025-03, with the labels that each got.

#414 chore: update the release workflow
  .github/workflows/create-release.yml
Labels: size/XS

#416 deps: bump all in main application
  poetry.lock
  pyproject.toml
Labels: size/L, evaluation requested, run-integration-test

#420 chore: grant issues write permission
  .github/workflows/pull-request-comment.yaml
Labels: size/XS

#422 refactor: expose redis from k3d in evaluation tests
  .github/workflows/pull-evaluation-tests.yaml
Labels: size/XS, lgtm

#415 feat: added usage tracking for token limit based on Redis
  src/agents/graph.py
  src/agents/memory/async_redis_checkpointer.py
  src/routers/conversations.py
  src/services/conversation.py
  src/services/usage.py
  src/utils/settings.py
  tests/blackbox/poetry.lock
  tests/blackbox/pyproject.toml
  tests/blackbox/src/common/config.py
  tests/blackbox/src/common/output.py
  tests/blackbox/src/evaluation/validator/usage_data.py
  tests/blackbox/src/run_evaluation.py
  tests/unit/agents/memory/test_async_redis_checkpointer.py
  tests/unit/routers/test_conversations.py
  tests/unit/services/test_conversation.py
  tests/unit/services/test_langfuse.py
  tests/unit/services/test_usage.py
Labels: size/XXL, evaluation requested, run-integration-test

#431 refactor: remove unuse decorator
  tests/unit/rag/reranker/test_reranker.py
Labels: size/XS

#432 deps: bump deepeval
  poetry.lock
Labels: size/S, run-integration-test

#437 chore: remove the integration tests for langfuse-based token count checks
  tests/integration/services/test_langfuse.py
Labels: run-integration-test

#435 fix: grammar of querries
  tests/blackbox/data/namespace-scoped/kyma_serverless_function_no_replicas/scenario.yml
  tests/integration/agents/fixtures/messages.py
  tests/integration/agents/kyma/test_kyma_agent.py
  tests/integration/agents/supervisor/test_planner.py
  tests/integration/agents/test_followup_questions.py
Labels: size/S, lgtm, evaluation requested, run-integration-test

#433 deps: fakeredis
  poetry.lock
Labels: size/XS, run-integration-test

#430 deps: shapely
  poetry.lock
Labels: size/M, run-integration-test

#434 deps: grpcio
  poetry.lock
Labels: size/L, evaluation requested, run-integration-test

#439 refactor: simplify code
  src/services/k8s.py
  tests/unit/agents/common/test_utils.py
  tests/unit/routers/test_conversations.py
Labels: size/S

#442 refactor: improve readability
  doc_indexer/src/utils/models.py
  doc_indexer/tests/unit/indexing/test_indexer.py
  src/routers/conversations.py
  src/services/k8s.py
  src/services/langfuse.py
  tests/unit/services/test_k8s.py
  tests/unit/utils/test_config.py
  tests/unit/utils/test_settings.py
Labels: size/M, lgtm

#443 refactor: proper override for json.CustomJSON.Encoder.default
  src/agents/graph.py
Labels: size/S

#401 chore: error handling planner
  src/agents/common/agent.py
  src/agents/summarization/summarization.py
  src/agents/supervisor/agent.py
  src/utils/response.py
  tests/unit/agents/common/test_agent.py
  tests/unit/agents/summarization/test_summarization.py
  tests/unit/agents/supervisor/test_supervisor_agent.py
  tests/unit/routers/test_conversations.py
  tests/unit/utils/test_response.py
Labels: size/M, cla: yes, lgtm, evaluation requested, run-integration-test

#450 chore: deleted integration tests for k8s client temp
  tests/integration/services/test_k8s_client_cert.py
Labels: run-integration-test

#438 refactor: move deprecated [tools.poetry] fields to [project]
  Dockerfile
  poetry.lock
  pyproject.toml
  scripts/shell/extract-python-version.sh
Labels: size/XXL, evaluation requested, run-integration-test

#441 refactor: remove unused utils
  src/agents/common/state.py
  src/agents/common/utils.py
  tests/unit/agents/common/test_state.py
  tests/unit/agents/common/test_utils.py
Labels: size/M, run-integration-test

#447 chore: handle recursive error limit error
  src/agents/common/agent.py
  src/agents/common/state.py
  src/agents/supervisor/agent.py
  tests/integration/agents/kyma/test_kyma_agent.py
  tests/unit/agents/common/test_agent.py
  tests/unit/agents/common/test_state.py
  tests/unit/agents/common/test_utils.py
Labels: evaluation requested, run-integration-test

#453 deps: add dist-upgrade to Dockerfile
  Dockerfile
Labels: evaluation requested

#456 feat: added custom prometheus metrics
  poetry.lock
  pyproject.toml
  src/main.py
  src/rag/retriever.py
  src/services/metrics.py
  src/services/usage.py
  tests/unit/rag/test_retriever.py
  tests/unit/routers/test_conversations.py
  tests/unit/services/test_usage.py
Labels: evaluation requested, run-integration-test

#459 feat: added LLM latency metric to prometheus metrics
  src/services/metrics.py
  src/services/usage.py
  tests/unit/services/test_usage.py
Labels: evaluation requested, run-integration-test

#461 fix: response converter not able to capture all YAML Blocks
  src/agents/common/response_converter.py
  tests/unit/agents/common/test_response_converter.py
Labels: evaluation requested, run-integration-test

#464 deps: regenerate lockfile
  poetry.lock
Labels: evaluation requested, run-integration-test

#467 fix: add missing assert statement in test
  Dockerfile
  poetry.lock
  tests/unit/agents/supervisor/test_supervisor_agent.py
Labels: evaluation requested, run-integration-test

#455 fix: planner responding directly without creating subtasks
  .gitignore
  scripts/python/companion.png
  scripts/python/generate_langgraph_diagram.py
  scripts/python/k8s_agent.png
  scripts/python/kyma_agent.png
  src/agents/common/constants.py
  src/agents/common/response_converter.py
  src/agents/common/state.py
  src/agents/graph.py
  src/agents/prompts.py
  src/agents/supervisor/agent.py
  src/agents/supervisor/prompts.py
  src/utils/response.py
  tests/integration/agents/supervisor/test_planner.py
  tests/integration/agents/test_gatekeeper_node.py
  tests/unit/agents/supervisor/test_supervisor_agent.py
  tests/unit/agents/test_graph.py
Labels: evaluation requested, run-integration-test
